### PR TITLE
added typescript type definition file

### LINKED ISSUE #44: Convert to TS from Flow

### PR DESCRIPTION
**Pull request by SCasarotto**
This PR add a typescript type definition to the repo.

closes #44

### CODE REVIEW

**Comment by MBach** [comment]
Great! Ping @plrdev?

**Review by plrdev — APPROVED** [review]
Thanks!

**Comment by dkarter** [comment]
Thank you for doing this! @plrdev is this scheduled for release?

**Comment by shabith** [comment]
Hi @plrdev, any plan to include this in the next release? When can it be?

**Pull request merged**
